apiVersion: v2
name: asr-monitoring
description: A Helm chart for Vietnamese ASR monitoring using Prometheus and Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: "15.10.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "6.32.2"
    repository: "https://grafana.github.io/helm-charts"
  - name: jaeger
    version: "0.58.0"
    repository: "https://jaegertracing.github.io/helm-charts" 